name       : haskell-old-locale
version    : 1.0.0.7
release    : 1
source     :
    - http://hackage.haskell.org/package/old-locale-1.0.0.7/old-locale-1.0.0.7.tar.gz : dbaf8bf6b888fb98845705079296a23c3f40ee2f449df7312f7f7f1de18d7b50
license    : BSD-3-Clause
component  : programming.haskell
summary    : This package provides the ability to adapt to locale conventions such as date and time formats. 
description: |
    This package provides the ability to adapt to locale conventions such as date and time formats. 
builddeps  :
    - haskell-cabal-install
setup      : |
    sed -i "s|4.9|4.10|" old-locale.cabal
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
